FROM php:7-apache

RUN a2enmod rewrite

# install the PHP extensions we need
RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev libpq-dev \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd mbstring pdo pdo_mysql zip opcache

WORKDIR /var/www/

#Install drush
RUN php -r "readfile('http://files.drush.org/drush.phar');" > drush
RUN chmod +x drush
RUN mv drush /usr/local/bin

RUN apt-get update -y && apt-get install -y mysql-client wget curl

# install composer
COPY composer-install.sh /usr/local/bin
RUN chmod +x /usr/local/bin/composer-install.sh
RUN composer-install.sh && cp composer.phar /usr/local/bin/composer




